version: 2.1

parameters:
  build_common:
    type: boolean
    default: false
  build_japan:
    type: boolean
    default: false

jobs:
  build-and-push-common-image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Building and pushing COMMON service image..."

  build-and-push-japan-image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Building and pushing JAPAN service image..."

workflows:
  version: 2
  build-services:
    when:
      condition:
        or:
          - << pipeline.parameters.build_common >>
          - << pipeline.parameters.build_japan >>
    jobs:
      - build-and-push-common-image:
          when:
            condition:
              equal: [true, << pipeline.parameters.build_common >>]
      - build-and-push-japan-image:
          when:
            condition:
              equal: [true, << pipeline.parameters.build_japan >>]
