version: 2.1

parameters:
  
  migrate_japan:
    type: boolean
    default: false
  migrate_latam:
    type: boolean
    default: false

jobs:
  migrations-latam:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Latam Service Message
          command: echo "Hello from Latam migrations!"

  migrations-japan:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Japan Service Message
          command: echo "Hello from Japan migrations!"

workflows:
  migration-pipeline:
    jobs:
      - migrations-japan:
          when:
            condition: << pipeline.parameters.migrate_japan >>
      - migrations-latam:
          when:
            condition: << pipeline.parameters.migrate_latam >>