version: 2.1

parameters:
  build_forecast:
    type: boolean
    default: false
  build_japan:
    type: boolean
    default: false

jobs:
  say-hello-forecast:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print forecast Service Message
          command: echo "Hello from forecast Service!"

  say-hello-japan:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Japan Service Message
          command: echo "Hello from Japan Service!"

workflows:
  service-forecast:
    when: << pipeline.parameters.build_forecast >>
    jobs:
      - say-hello-forecast

  service-japan:
    when: << pipeline.parameters.build_japan >>
    jobs:
      - say-hello-japan
