version: 2.1

parameters:
  
  migrate_japan:
    type: boolean
    default: false
  migrate_latam:
    type: boolean
    default: false

jobs:
  pre-changes:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Debug Path Filtering
          command: |
            ls -la
            echo "Pipeline parameters:"
            echo "migrate_forecast: << pipeline.parameters.migrate_japan >>"

  post-changes:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Debug Path Filtering
          command: |
            ls -la
            echo "Pipeline parameters:"
            echo "migrate_forecast: << pipeline.parameters.migrate_latam >>"

  migrations-latam:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Latam Service Message
          command: echo "Hello from Latam migrations!"

  migrations-japan:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Japan Service Message
          command: echo "Hello from Japan migrations!"

workflows:
  pre-changes:
    jobs:
      - pre-changes
  post-changes:
    requires:
      - pre-changes
    when: << pipeline.parameters.migrate_latam >>
    jobs:
      - post-changes


  service-latam:
    when: << pipeline.parameters.migrate_latam >>
    requires:
      - pre-changes
      - post-changes
    jobs:
      - migrations-latam


  service-japan:
    when: << pipeline.parameters.migrate_japan >>
    requires:
      - pre-changes
      - post-changes
    jobs:
      - migrations-japan
