version: 2.1

parameters:
  migrate_japan:
    type: boolean
    default: false
  migrate_latam:
    type: boolean
    default: false

jobs:
  debug-params:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Params
          command: |
            echo "migrate japan: << pipeline.parameters.migrate_japan >>"
            echo "migrate latam: << pipeline.parameters.migrate_latam >>"

  # migrations-latam:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - run:
  #         name: Print Latam Service Message
  #         command: echo "Hello from Latam migrations!"

  # migrations-japan:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - run:
  #         name: Print Japan Service Message
  #         command: echo "Hello from Japan migrations!"

workflows:
  migration-pipeline:
    jobs:
      - debug-params

      # - migrations-japan:
      #     when:
      #       condition: << pipeline.parameters.migrate_japan >>
      # - migrations-latam:
      #     when:
      #       condition: << pipeline.parameters.migrate_latam >>