version: 2.1

parameters:
  migrate_forecast:
    type: boolean
    default: false
  migrate_japan:
    type: boolean
    default: false

jobs:
  migration-changes:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Debug Path Filtering
          command: |
            echo "Base revision: main"
            git fetch origin main
            git diff --name-only origin/main
            echo "Pipeline parameters:"
            echo "migrate_forecast: << pipeline.parameters.migrate_forecast >>"
            echo "migrate_japan: << pipeline.parameters.migrate_japan >>"

  migrations-forecast:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print forecast Service Message
          command: echo "Hello from forecast migrations!"

  migrations-japan:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Japan Service Message
          command: echo "Hello from Japan migrations!"

workflows:
  main-workflow:
    jobs:
      - migration-changes

  service-forecast:
    when: << pipeline.parameters.migrate_forecast >>
    jobs:
      - migrations-forecast

  service-japan:
    when: << pipeline.parameters.migrate_japan >>
    jobs:
      - migrations-japan
