version: 2.1

parameters:
  migrate_forecast:
    type: boolean
    default: false
  migrate_japan:
    type: boolean
    default: false

jobs:
  migrations-forecast:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print forecast Service Message
          command: echo "Hello from forecast migrations!"

  migrations-japan:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Japan Service Message
          command: echo "Hello from Japan migrations!"

workflows:
  # service-forecast:
  #   when: << pipeline.parameters.migrate_forecast >>
  #   jobs:
  #     - migrations-forecast

  # service-japan:
  #   when: << pipeline.parameters.migrate_japan >>
  #   jobs:
  #     - migrations-japan
