version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  detect-market:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install CircleCI continuation plugin
          command: |
            circleci setup
            circleci update
            circleci plugin install continuation
      - run:
          name: Detect updated market path and continue
          command: |
            git fetch origin main --depth=1
            if git diff --name-only origin/main...HEAD | grep -q "src/etl/japan/"; then
              echo 'Detected market: japan'
              circleci continuation continue -c src/etl/.circleci/continue_config_japan.yml -p '{}'
            elif git diff --name-only origin/main...HEAD | grep -q "src/etl/common/"; then
              echo 'Detected market: common'
              circleci continuation continue -c src/etl/.circleci/continue_config_common.yml -p '{}'
            else
              echo 'No relevant changes detected. Exiting.'
              circleci-agent step halt
            fi

workflows:
  setup:
    jobs:
      - detect-market
