version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  detect-market:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Detect updated market path
          command: |
            git fetch origin main --depth=1
            if git diff --name-only origin/main...HEAD | grep -q "src/etl/japan/"; then
              echo 'export MARKET=japan' >> $BASH_ENV
            elif git diff --name-only origin/main...HEAD | grep -q "src/etl/common/"; then
              echo 'export MARKET=common' >> $BASH_ENV
            else
              echo 'export MARKET=none' >> $BASH_ENV
            fi
      - run:
          name: Save market as pipeline parameter
          command: |
            source $BASH_ENV
            echo '{"market": "'${MARKET}'"}' > pipeline-params.json
      - continuation/continue:
          configuration_path: src/etl/.circleci/continue_config.yml
          parameters: pipeline-params.json

workflows:
  setup:
    jobs:
      - detect-market
