version: 2.1

jobs:
  echo-image:
    docker:
      - image: cimg/python:3.10
    parameters:
      target:
        type: string
      path_filter:
        type: string
    steps:
      - checkout
      - run:
          name: Check for file changes under << parameters.path_filter >>
          command: |
            echo "Checking if changes affected << parameters.path_filter >>"
            if git diff --name-only HEAD^ | grep -q "<< parameters.path_filter >>"; then
              echo "🔧 This is the ETL job for << parameters.target >>"
            else
              echo "❌ No relevant changes, skipping << parameters.target >> job"
              circleci-agent step halt
            fi

workflows:
  etl-build:
    jobs:
      - echo-image:
          name: echo-common
          target: common
          path_filter: src/etl/common/

      - echo-image:
          name: echo-japan
          target: japan
          path_filter: src/etl/japan/
