version: 2.1

# Define the dynamic pipeline parameters
parameters:
  build_common:
    type: string
    default: "false"
  build_japan:
    type: string
    default: "false"

# JOBS
jobs:
  check-paths:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Fetch base branch
          command: |
            git fetch origin main

      - run:
          name: Detect changed paths
          command: |
            echo "Checking changed files against main branch..."
            CHANGED_FILES=$(git diff --name-only origin/main...HEAD)

            echo "Changed files:"
            echo "$CHANGED_FILES"

            if echo "$CHANGED_FILES" | grep -q '^services/common/'; then
              echo 'export BUILD_COMMON="true"' >> $BASH_ENV
            fi

            if echo "$CHANGED_FILES" | grep -q '^services/japan/'; then
              echo 'export BUILD_JAPAN="true"' >> $BASH_ENV
            fi

  build-and-push-common-image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build and Push Common Image
          command: echo "Building and pushing Common Service image..."

  build-and-push-japan-image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build and Push Japan Image
          command: echo "Building and pushing Japan Service image..."

# WORKFLOWS
workflows:
  version: 2
  build:
    jobs:
      - check-paths

      - build-and-push-common-image:
          requires:
            - check-paths
          when:
            condition:
              equal: ["true", << pipeline.parameters.build_common >>]

      - build-and-push-japan-image:
          requires:
            - check-paths
          when:
            condition:
              equal: ["true", << pipeline.parameters.build_japan >>]
