version: 2.1
orbs:
  path-filtering: circleci/path-filtering@0.1.3

jobs:
  build-and-push-common-image:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Build and push common image
          command: |
            echo "Building and pushing common image for tag: common_${CIRCLE_SHA1::7}"
            # Add your docker build/push commands here
  build-and-push-japan-image:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Build and push japan image
          command: |
            echo "Building and pushing japan image for tag: japan_${CIRCLE_SHA1::7}"
            # Add your docker build/push commands here

workflows:
  etl:
    jobs:
      - path-filtering/filter:
          name: check-changes
          mapping: |
            src/etl/common/.* build_common true
            src/etl/japan/.* build_japan true
          base-revision: main
      - build-and-push-common-image:
          requires:
            - check-changes
          filters:
            branches:
              only: /.*/
          when: << pipeline.parameters.build_common >>
      - build-and-push-japan-image:
          requires:
            - check-changes
          filters:
            branches:
              only: /.*/
          when: << pipeline.parameters.build_japan >>
