version: 2.1

jobs:
  build-and-push-common-image:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Build and push common image
          command: |
            echo "Building and pushing common image for tag: common_${CIRCLE_SHA1::7}"

  build-and-push-japan-image:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Build and push japan image
          command: |
            echo "Building and pushing japan image for tag: japan_${CIRCLE_SHA1::7}"

workflows:
  etl:
    jobs:
      - build-and-push-common-image:
          filters:
            paths:
              - src/etl/common/**

      - build-and-push-japan-image:
          filters:
            paths:
              - src/etl/japan/**
