version: 2.1
orbs:
  path-filtering: circleci/path-filtering@0.1.5

jobs:
  build-and-push-common-image:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Check if build_common is set
          command: |
            if [ "${CIRCLE_PIPELINE_PARAMETERS.build_common}" != "true" ]; then
              echo "Skipping: build_common is not set."
              exit 0
            fi
      - run:
          name: Build and push common image
          command: |
            echo "Building and pushing common image for tag: common_${CIRCLE_SHA1::7}"
  build-and-push-japan-image:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Check if build_japan is set
          command: |
            if [ "${CIRCLE_PIPELINE_PARAMETERS.build_japan}" != "true" ]; then
              echo "Skipping: build_japan is not set."
              exit 0
            fi
      - run:
          name: Build and push japan image
          command: |
            echo "Building and pushing japan image for tag: japan_${CIRCLE_SHA1::7}"

workflows:
  filter-changes:
    jobs:
      - path-filtering/filter:
          name: check-changes
          mapping: |
            src/etl/common/.* build_common true
            src/etl/japan/.* build_japan true
          base-revision: main
  etl:
    jobs:
      - build-and-push-common-image
      - build-and-push-japan-image
