version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.3.0  # Official CircleCI path-filtering orb

# Define parameters that will be passed after path-filtering
parameters:
  build_common:
    type: boolean
    default: false
  build_japan:
    type: boolean
    default: false
  test_all:
    type: boolean
    default: false

jobs:
  test-lint-checks:
    docker:
      - image: cimg/python:3.11  # main container
        name: market_etl
      - image: localstack/localstack:latest  # localstack service
        name: localstack
        environment:
          SERVICES: s3, secretsmanager
          EDGE_PORT: 4566
      - image: postgres:13  # postgres service
        name: postgres
        environment:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            pip install -r requirements.txt
      - run:
          name: Install Sqitch
          command: |
            sudo apt-get update && sudo apt-get install -y sqitch libpq-dev
      - run:
          name: Wait for PostgreSQL
          command: |
            for i in {1..10}; do
              pg_isready -h postgres -p 5432 && break
              echo "Waiting for PostgreSQL to be ready..."
              sleep 3
            done
      - run:
          name: Deploy Forecast Schema
          command: |
            sqitch deploy --chdir db_migrations/forecast
      - run:
          name: Deploy Japan Schema
          command: |
            sqitch deploy --chdir db_migrations/japan
      - run:
          name: Run Tests + Lint
          command: |
            chmod +x ./test_and_lint_checks.sh
            ./test_and_lint_checks.sh src/etl/ tests/

workflows:
  setup-workflow:
    jobs:

      - path-filtering/filter:
          name: etl-pipeline-filter
          base-revision: main
          config-path: src/etl/.circleci/etl-config.yml
          mapping: |
            db_migrations/.* test_all true
            src/etl/common/.* build_common true test_all true
            src/etl/japan/.* build_japan true test_all true
            src/etl/latam/.* build_latam true test_all true

