version: 2.1

jobs:
  detect-market:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Detect updated market path
          command: |
            git fetch origin main --depth=1
            if git diff --name-only origin/main...HEAD | grep -q "src/etl/japan/"; then
              echo "japan" > market.txt
            elif git diff --name-only origin/main...HEAD | grep -q "src/etl/common/"; then
              echo "common" > market.txt
            else
              echo "none" > market.txt
            fi
      - persist_to_workspace:
          root: .
          paths:
            - market.txt

  build-and-push-etl-image:
    docker:
      - image: cimg/python:3.9-slim
    working_directory: ~/market_etl
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Read selected market
          command: |
            MARKET=$(cat /workspace/market.txt)
            echo "Detected market: $MARKET"
            echo "export MARKET=$MARKET" >> $BASH_ENV
      - run:
          name: setup operations-0 aws credentials
          command: |
            echo "This is final step, tag : $MARKET_${CIRCLE_SHA1::7}" 


workflows:
  version: 2
  etl:
    jobs:
      - detect-market
      - build-and-push-etl-image:
          requires:
            - detect-market
