version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.3.0  # Official CircleCI path-filtering orb

# Define parameters that will be passed after path-filtering
parameters:
  build_common:
    type: boolean
    default: false
  build_japan:
    type: boolean
    default: false

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          name: etl-changes
          base-revision: main
          config-path: src/etl/.circleci/etl-config.yml
          mapping: |
            src/etl/common/.* build_common true
            src/etl/japan/.* build_japan true

