version: 2.1

jobs:
  build-and-push-common-image:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Build and push common image
          command: |
            echo "Building and pushing common image for tag: common_${CIRCLE_SHA1::7}"
            # Add your docker build/push commands here

workflows:
  etl:
    jobs:
      - build-and-push-common-image
