version: 2.1

parameters:
  market:
    type: string
    default: none

jobs:
  build-and-push-common-image:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Check if market is common
          command: |
            if [ "<< pipeline.parameters.market >>" != "common" ]; then
              echo "Skipping: market is not common"
              exit 0
            fi
      - run:
          name: Build and push common image
          command: |
            echo "Building and pushing common image for tag: common_${CIRCLE_SHA1::7}"
            # Add your docker build/push commands here

  build-and-push-japan-image:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Check if market is japan
          command: |
            if [ "<< pipeline.parameters.market >>" != "japan" ]; then
              echo "Skipping: market is not japan"
              exit 0
            fi
      - run:
          name: Build and push japan image
          command: |
            echo "Building and pushing japan image for tag: japan_${CIRCLE_SHA1::7}"
            # Add your docker build/push commands here

workflows:
  version: 2
  etl:
    jobs:
      - build-and-push-common-image:
          filters:
            branches:
              only: /.*/
      - build-and-push-japan-image:
          filters:
            branches:
              only: /.*/
