version: 2.1

parameters:
  build_common:
    type: boolean
    default: false
  build_japan:
    type: boolean
    default: false
  build_latam:
    type: boolean
    default: false
  test_all:
    type: boolean
    default: false

jobs:
  debug-params:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Params
          command: |
            echo "build_common: << pipeline.parameters.build_common >>"
            echo "build_japan: << pipeline.parameters.build_japan >>"
            echo "build_latam: << pipeline.parameters.build_latam >>"
            echo "test_all: << pipeline.parameters.test_all >>"

  run-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print all tests Message
          command: echo "Running tests for all markets!"

  build-japan:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Japan Market Message
          command: echo "Hello from Japan Market!"

  build-latam:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Latam Market Message
          command: echo "Hello from Latam Market!"

  build-common:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Common Market Message
          command: echo "Hello from Common Market!"

workflows:
  etl-pipeline:
    jobs:
      # Always run debug to see what parameters were set
      - debug-params

      # Run tests if any changes detected
      - run-tests:
          when:
            or:
              - << pipeline.parameters.test_all >>
              - << pipeline.parameters.build_common >>
              - << pipeline.parameters.build_japan >>
              - << pipeline.parameters.build_latam >>

      # Build jobs only run if their parameter is true and tests pass
      - build-common:
          requires:
            - run-tests
          when:
            condition: << pipeline.parameters.build_common >>

      - build-japan:
          requires:
            - run-tests
          when:
            condition: << pipeline.parameters.build_japan >>

      - build-latam:
          requires:
            - run-tests
          when:
            condition: << pipeline.parameters.build_latam >>