version: 2.1

parameters:
  build_common:
    type: boolean
    default: false
  build_japan:
    type: boolean
    default: false
  build_latam:              # <-- ADD THIS
    type: boolean
    default: false
  test_all:
    type: boolean
    default: false

jobs:
  run-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print all tests Message
          command: echo "Running tests for all markets!"

  build-japan:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Japan Market Message
          command: echo "Hello from Japan Market!"

  build-latam:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Latam Market Message
          command: echo "Hello from Latam Market!"

  build-common:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Common Market Message
          command: echo "Hello from Common Market!"

workflows:
  etl-pipeline:
    jobs:
      - run-tests:
          when:
            condition: << pipeline.parameters.test_all >>

      - build-common:
          requires:
            - run-tests
          when:
            condition: << pipeline.parameters.build_common >>

      - build-japan:
          requires:
            - run-tests
          when:
            condition: << pipeline.parameters.build_japan >>

      - build-latam:
          requires:
            - run-tests
          when:
            condition: << pipeline.parameters.build_latam >>